# Generated by Django 4.0.3 on 2022-03-18 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_clone', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='comment',
            new_name='comment_id',
        ),
    ]
