# Generated by Django 4.0.3 on 2022-03-18 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_clone', '0002_rename_comment_reply_comment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='comment_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='youtube_clone.comment'),
        ),
    ]
