# Generated by Django 4.0.3 on 2022-03-18 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_clone', '0003_alter_reply_comment_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='comment_id',
            new_name='comment',
        ),
    ]
